export const flyers = [
  {
    title: 'Confusion',
    date: '2025.09.28',
    venue: 'Precious Hall (Sapporo)',
    imgBaseName: '250928_confusion',
    alt: 'confusion',
  },
  {
    title: 'Joy',
    date: '2025.09.20',
    venue: 'Precious Hall (Sapporo)',
    imgBaseName: '250920_joy',
    alt: 'joy',
  },
  {
    title: <span style={{fontSize: "1.2rem"}}>Island 3rd Anniv. Party</span>,
    date: '2025.09.20',
    venue: 'Dining Bar Island (Sapporo)',
    imgBaseName: '250920_island3rdanniversary',
    alt: 'island 3rd anniv',
  },
  {
    title: 'Big Fun',
    date: '2025.09.07',
    venue: 'Hakkenzan Kajuen (Sapporo)',
    imgBaseName: '250907_bigfun',
    alt: 'big fun',
  },
  {
    title: '整理整頓展',
    date: '2025.08.30-31',
    venue: 'PON PIYEHE house (Sapporo)',
    imgBaseName: '250830_seiriseitonten',
    alt: '整理整頓展',
  },
  {
    title: 'Confusion',
    date: '2025.08.17',
    venue: 'Precious Hall (Sapporo)',
    imgBaseName: '250817_confusion',
    alt: 'confusion',
  },
  {
    title: 'Signal',
    date: '2025.08.01',
    venue: 'Precious Hall (Sapporo)',
    imgBaseName: '250801_signal',
    alt: 'signal',
  },
  {
    title: 'Joy',
    date: '2025.07.20',
    venue: 'Precious Hall (Sapporo)',
    imgBaseName: '250720_joy',
    alt: 'joy',
  },
  {
    title: 'Confusion',
    date: '2025.07.19',
    venue: 'Precious Hall (Sapporo)',
    imgBaseName: '250719_confusion',
    alt: 'confusion',
  },
  {
    title: 'Auditory Lounge',
    date: '2025.07.16-30',
    venue: 'Precious Hall (Sapporo)',
    imgBaseName: '2507_auditorylounge_01',
    alt: 'auditory lounge',
  },
  {
    title: '',
    date: '',
    venue: '',
    imgBaseName: '2507_auditorylounge_02',
    alt: 'auditory lounge',
  },
  {
    title: <span style={{fontSize: "1.3rem"}}>Minimalism is Space</span>,
    date: '2025.07.11',
    venue: 'Precious Hall (Sapporo)',
    imgBaseName: '250711_minimalismisspace',
    alt: 'minimalism is space',
  },
  {
    title: 'Spiral',
    date: '2025.06.20',
    venue: 'Precious Hall (Sapporo)',
    imgBaseName: '250620_spiral',
    alt: 'spiral',
  },
  {
    title: 'M.O.P.S.',
    date: '2025.06.13',
    venue: 'Precious Hall (Sapporo)',
    imgBaseName: '250613_mops_01',
    alt: 'mops',
  },
  {
    title: '',
    date: '',
    venue: '',
    imgBaseName: '250613_mops_02',
    alt: 'mops',
  },
  {
    title: <span style={{fontSize: "1.1rem"}}>Precious Hall 32th Anniv.</span>,
    date: '2025.06.05',
    venue: 'Precious Hall (Sapporo)',
    imgBaseName: '250605_precioushall32thanniversary_01',
    alt: 'precious hall 32th anniv party',
  },
  {
    title: '',
    date: '',
    venue: '',
    imgBaseName: '250605_precioushall32thanniversary_02',
    alt: 'precious hall 32th anniv party',
  },
  {
    title: 'Joy',
    date: '2025.05.31',
    venue: 'Precious Hall (Sapporo)',
    imgBaseName: '250531_joy',
    alt: 'joy',
  },
  {
    title: 'Misa presents 山菜ナイト',
    date: '2025.05.06',
    venue: 'Neo Sakaba Walts (Sapporo)',
    imgBaseName: '250506_sansainight',
    alt: '山菜ナイト',
  },
  {
    title: 'Joy',
    date: '2025.04.12',
    venue: 'Precious Hall (Sapporo)',
    imgBaseName: '250412_joy',
    alt: 'joy',
  },
  {
    title: '2DX',
    date: '2025.04.11',
    venue: 'Panacea (Sapporo)',
    imgBaseName: '250411_2dx',
    alt: '2dx',
  },
  {
    title: 'Spiral',
    date: '2025.04.04',
    venue: 'Precious Hall (Sapporo)',
    imgBaseName: '250404_spiral',
    alt: 'spiral',
  },
  {
    title: 'Joy',
    date: '2025.03.29',
    venue: 'Precious Hall (Sapporo)',
    imgBaseName: '250329_joy',
    alt: 'joy',
  },
  {
    title: 'N & M Wedding Party',
    date: '2025.02.09',
    venue: 'Sasazuka Bowl (Tokyo)',
    imgBaseName: '250209_nmweddingparty',
    alt: 'n & m wedding party',
  },
  {
    title: 'Infinity Rhythm',
    date: '2025.02.01',
    venue: 'Precious Hall (Sapporo)',
    imgBaseName: '250201_infinityrhythm_01',
    alt: 'infinity rhythm_01',
  },
  {
    title: '',
    date: '',
    venue: '',
    imgBaseName: '250201_infinityrhythm_02',
    alt: 'infinity rhythm_01',
  },
  {
    title: <span style={{fontSize: "1.2rem"}}>Laidbackfloor meets Folflore</span>,
    date: '2025.01.25',
    venue: 'Precious Hall (Sapporo)',
    imgBaseName: '250125_laidbackfloor',
    alt: 'laidbackfloor meets folflore',
  },
  {
    title: 'Spiral',
    date: '2025.01.24',
    venue: 'Precious Hall (Sapporo)',
    imgBaseName: '250124_spiral',
    alt: 'spiral',
  },
  {
    title: '2DX',
    date: '2025.01.10',
    venue: 'Panacea (Sapporo)',
    imgBaseName: '250110_2dx',
    alt: '2dx',
  },
  {
    title: 'End Of The Year 2024',
    date: '2024.12.29',
    venue: 'Precious Hall (Sapporo)',
    imgBaseName: '241229_preciousendofyear_01',
    alt: 'end of the year 2024',
  },
  {
    title: '',
    date: '',
    venue: '',
    imgBaseName: '241229_preciousendofyear_02',
    alt: 'end of year 2024',
  },
  {
    title: 'Cloud 9',
    date: '2024.12.28',
    venue: 'Precious Hall (Sapporo)',
    imgBaseName: '241228_cloud9',
    alt: 'cloud 9',
  },
  {
    title: 'Number',
    date: '2024.12.27',
    venue: 'Provo (Sapporo)',
    imgBaseName: '241227_number',
    alt: 'number',
  },
  {
    title: 'Archiv',
    date: '2024.12.20',
    venue: 'Precious Hall (Sapporo)',
    imgBaseName: '241220_archiv',
    alt: 'archiv',
  },
  {
    title: '3DX',
    date: '2024.11.16',
    venue: 'Panacea (Sapporo)',
    imgBaseName: '241116_3dx',
    alt: '3dx',
  },
  {
    title: 'Joy & Beyond',
    date: '2017.12.03',
    venue: <span style={{fontSize: "0.85rem"}}>Geijutsu No Mori Art Hall (Sapporo)</span>,
    imgBaseName: '171203_joyandbeyond',
    alt: 'Joy & Beyond',
  },
  {
    title: <span style={{fontSize: "1.2rem"}}>Provo 14th Anniv. Party</span>,
    date: '2017.11.17-24',
    venue: 'Provo / Precious Hall (Sapporo)',
    imgBaseName: '171124_provo14thanniversary',
    alt: 'Provo 14th Anniv. Party',
  },
  {
    title: 'マンモス2016',
    date: '2016.11.19',
    venue: 'Nishisawa Suisan Bldg. (Sapporo)',
    imgBaseName: '161119_mammoth2016',
    alt: 'マンモス2016',
  },
  {
    title: '',
    date: '',
    venue: '',
    imgBaseName: '161119_mammoth2016_tt',
    alt: 'マンモス2016タイムテーブル',
  },
  {
    title: 'bo nen',
    date: '2015.12.27',
    venue: 'Spiritual Lounge (Sapporo)',
    imgBaseName: '151227_bonen',
    alt: 'bo nen',
  },
]