export const decks = [
  {
    brand: 'Alien Workshop',
    id: 'alien_workshop',
    model: 'Joey Guevara',
    title: 'AI',
    imgBaseName: 'alien_workshop_joey_guevara_ai',
    alt: 'Alien Workshop Joey Guevara AI',
  },
  {
    brand: 'Alien Workshop',
    model: 'Team',
    title: 'Photosynthesis 25th',
    imgBaseName: 'alien_workshop_photosynthesis_25th',
    alt: 'Alien Workshop Team Photosynthesis 25th',
  },
  {
    brand: 'Alien Workshop',
    model: 'Team',
    title: 'Racer Slick',
    imgBaseName: 'alien_workshop_racer_slick',
    alt: 'Alien Workshop Team Racer Slick',
  },
  {
    brand: 'Alien Workshop',
    model: 'Yaje Popson',
    title: 'Arjuna',
    imgBaseName: 'alien_workshop_yaje_popson_arjuna',
    alt: 'Alien Workshop Yaje Popson Arjuna',
  },
  {
    brand: 'Alva',
    id: 'alva_skates',
    model: 'Team',
    title: 'Alva Beta Cobalt Blue',
    imgBaseName: 'alva_alva_beta_cobalt_blue',
    alt: 'Alva Team Alva Beta Cobalt Blue',
  },
  {
    brand: 'Antihero',
    id: 'antihero',
    model: 'Austin Kanfoush',
    title: 'Dawn Of The Pigeon',
    imgBaseName: 'antihero_austin_kanfoush_dawn_of_the_pigeon',
    alt: 'Antihero Austin Kanfoush Dawn Of The Pigeon',
  },
  {
    brand: 'Antihero',
    model: 'Frank Gerwer',
    title: 'Grimplestix Barbarians',
    imgBaseName: 'antihero_frank_gerwer_grimplestix_barbarians',
    alt: 'Antihero Frank Gerwer Grimplestix Barbarians',
  },
  {
    brand: 'Antihero',
    model: 'Grant Taylor',
    title: 'GT DBX',
    imgBaseName: 'antihero_grant_taylor_gt_dbx',
    alt: 'Antihero Grant Taylor GT DBX',
  },
  {
    brand: 'Antihero',
    model: 'Nick Matthews',
    title: 'P2: Judgement Day',
    imgBaseName: 'antihero_nick_matthews_p2_judgement_day',
    alt: 'Antihero Nick Matthews P2: Judgement Day',
  },
  {
    brand: 'Antihero',
    model: 'Peter Hewitt',
    title: 'Cascade',
    imgBaseName: 'antihero_peter_hewitt_cascade',
    alt: 'Antihero Peter Hewitt Cascade',
  },
  {
    brand: 'Antihero',
    model: 'Taylor Makalassi',
    title: 'DBX',
    imgBaseName: 'antihero_taylor_makalassi_dbx',
    alt: 'Antihero Taylor Makalassi DBX',
  },
  {
    brand: 'April',
    id: 'april',
    model: 'Dashawn Jordan',
    title: 'Aim',
    imgBaseName: 'april_dashawn_jordan_aim',
    alt: 'April Dashawn Jordan Aim',
  },
  {
    brand: 'April',
    model: 'Kai Kishi',
    title: 'Figures',
    imgBaseName: 'april_kai_kishi_figures',
    alt: 'April Kai Kishi Figures',
  },
  {
    brand: 'April',
    model: 'Yuto Horigome',
    title: 'Yuto By Ema Gaspar',
    imgBaseName: 'april_yuto_horigome_yuto_by_ema_gaspar',
    alt: 'April Yuto Horigome Yuto By Ema Gaspar',
  },
  {
    brand: 'Baker',
    id: 'baker',
    model: 'Team',
    title: 'Brand Logo Black',
    imgBaseName: 'baker_team_brand_logo_black',
    alt: 'Baker Team Brand Logo Black',
  },
  {
    brand: 'Baker',
    model: 'Riley Hawk',
    title: 'Shep Dawgs',
    imgBaseName: 'baker_riley_hawk_shep_dawgs',
    alt: 'Baker Riley Hawk Shep Dawgs',
  },
  {
    brand: 'Baker',
    model: 'Rowan Zorilla',
    title: 'Brain Rabies',
    imgBaseName: 'baker_rowan_zorilla_brain_rabies',
    alt: 'Baker Rowan Zorilla Brain Rabies',
  },
  {
    brand: 'Birdhouse',
    id: 'birdhouse',
    model: 'Aaron "Jaws" Hamoki',
    title: 'Lock In',
    imgBaseName: 'birdhouse_aaron_jaws_hamoki_lock_in',
    alt: 'Birdhouse Aaron Jaws Hamoki Lock In',
  },
  {
    brand: 'Birdhouse',
    model: 'Greyson Fletcher',
    title: 'Freeze Guy',
    imgBaseName: 'birdhouse_greyson_fletcher_freeze_guy',
    alt: 'Birdhouse Greyson Fletcher Freeze Guy',
  },
  {
    brand: 'Birdhouse',
    model: 'Lizzle Armanto',
    title: 'Sewn',
    imgBaseName: 'birdhouse_lizzle_armanto_neckless',
    alt: 'Birdhouse Lizzle Armanto Neckless',
  },
  {
    brand: 'Birdhouse',
    model: 'Lizzle Armanto',
    title: 'Sewn',
    imgBaseName: 'birdhouse_lizzle_armanto_sewn',
    alt: 'Birdhouse Lizzle Armanto Sewn',
  },
  {
    brand: 'Birdhouse',
    model: 'Shawn Hale',
    title: 'Office',
    imgBaseName: 'birdhouse_shawn_hale_office',
    alt: 'Birdhouse Shawn Hale Office',
  },
  {
    brand: 'Birdhouse',
    model: 'Tate Carew',
    title: 'Bomber XL',
    imgBaseName: 'birdhouse_tate_carew_bomber_xl',
    alt: 'Birdhouse Tate Carew Bomber XL',
  },
  {
    brand: 'Black Label',
    id: 'black_label',
    model: 'Team',
    title: 'Shredded Barcode Egg',
    imgBaseName: 'black_label_team_shredded_barcode_egg',
    alt: 'Black Label Team Shredded Barcode Egg',
  },
  {
    brand: 'Blueprint',
    id: 'blueprint',
    model: 'Team',
    title: 'Home Heart Black / End',
    imgBaseName: 'blueprint_team_home_heart_black_end',
    alt: 'Blueprint Team Home Heart Black / End',
  },
  {
    brand: 'Blueprint',
    model: 'Team',
    title: 'Sky x Mlsl Holographic Bird',
    imgBaseName: 'blueprint_team_skyxmlsl_holographic_bird',
    alt: 'Blueprint Team Sky x Mlsl Holographic Bird',
  },
  {
    brand: 'Chocolate',
    id: 'chocolate',
    model: 'Vincent Alvarez',
    title: 'Vision Quest',
    imgBaseName: 'chocolate_vincent_alvarez_vision_quest',
    alt: 'Chocolate Vincent Alvarez Vision Quest',
  },
  {
    brand: 'Deathwish',
    id: 'deathwish',
    model: 'Brian O\'Dwyer',
    title: 'Lineage',
    imgBaseName: 'deathwish_brian_odwyer_lineage',
    alt: 'Deathwish Brian O\'Dwyer Lineage',
  },
  {
    brand: 'Deathwish',
    model: 'Erik Ellington',
    title: 'Lovers',
    imgBaseName: 'deathwish_erik_ellington_lovers',
    alt: 'Deathwish Erik Ellington Lovers',
  },
  {
    brand: 'Deathwish',
    model: 'Jamie Foy',
    title: 'Flamingo ',
    imgBaseName: 'deathwish_jamie_foy_flamingo ',
    alt: 'Deathwish Jamie Foy Flamingo ',
  },
  {
    brand: 'Deathwish',
    model: 'Jamie Foy',
    title: 'Hemi',
    imgBaseName: 'deathwish_jamie_foy_hemi',
    alt: 'Deathwish Jamie Foy Hemi',
  },
  {
    brand: 'Deathwish',
    model: 'Jon Dickson',
    title: 'Pale Rider',
    imgBaseName: 'deathwish_jon_dickson_pale_rider',
    alt: 'Deathwish Jon Dickson Pale Rider',
  },
  {
    brand: 'Deathwish',
    model: 'Team',
    title: 'Deathspray Black / Red',
    imgBaseName: 'deathwish_team_deathspray_black_red',
    alt: 'Deathwish Team Deathspray Black / Red',
  },
  {
    brand: 'Deathwish',
    model: 'Team',
    title: 'Gang Spray Black / White',
    imgBaseName: 'deathwish_team_gang_spray_black_white',
    alt: 'Deathwish Team Gang Spray Black / White',
  },
  {
    brand: 'Deathwish',
    model: 'Yuri Facchini',
    title: 'Take Cover',
    imgBaseName: 'deathwish_yuri_facchini_take_cover',
    alt: 'Deathwish Yuri Facchini Take Cover',
  },
  {
    brand: 'DGK',
    id: 'dgk',
    model: 'Boo Johnson',
    title: 'Unity',
    imgBaseName: 'dgk_boo_johnson_unity',
    alt: 'DGK Boo Johnson Unity',
  },
  {
    brand: 'DGK',
    model: 'Dane Vaughn',
    title: 'One Player',
    imgBaseName: 'dgk_dane_vaughn_one_player',
    alt: 'DGK Dane Vaughn One Player',
  },
  {
    brand: 'DGK',
    model: 'DGK x Ironlak',
    title: 'Lacquer',
    imgBaseName: 'dgk_dgkxironlak_lacquer',
    alt: 'DGK DGK x Ironlak Lacquer',
  },
  {
    brand: 'DGK',
    model: 'John Shanahan',
    title: 'Triplets',
    imgBaseName: 'dgk_john_shanahan_triplets',
    alt: 'DGK John Shanahan Triplets',
  },
  {
    brand: 'DGK',
    model: 'Team',
    title: 'Frost',
    imgBaseName: 'dgk_team_frost',
    alt: 'DGK Team Frost',
  },
  {
    brand: 'DGK',
    model: 'Kevin Bilyeu',
    title: 'Transportation',
    imgBaseName: 'dgk_kevin_bilyeu_transportation',
    alt: 'DGK Kevin Bilyeu Transportation',
  },
  {
    brand: 'Edglrd',
    id: 'edglrd',
    model: 'Team',
    title: 'Hell Hound Blue',
    imgBaseName: 'edglrd_team_hell_hound_blue',
    alt: 'Edglrd Team Hell Hound Blue',
  },
  {
    brand: 'Evisen',
    model: 'Team',
    title: 'Don\'t Kill My Vibe',
    imgBaseName: 'evisen_team_dont_kill_my_vibe',
    alt: 'Evisen Team Don\'t Kill My Vibe',
  },
  {
    brand: 'FTC',
    model: 'Team',
    title: 'FTC x Yoon Hyup Summer Nights',
    imgBaseName: 'ftc_team_ftc_x_yoon_hyup_summer_nights',
    alt: 'FTC Team FTC x Yoon Hyup Summer Nights',
  },
  {
    brand: 'Fucking Awesome',
    model: 'Team',
    title: 'Wanto Throw Up Man',
    imgBaseName: 'fucking_awesome_team_wanto_throw_up_man',
    alt: 'Fucking Awesome Team Wanto Throw Up Man',
  },
  {
    brand: 'Evisen',
    model: 'Team',
    title: 'Falling Graphite',
    imgBaseName: 'evisen_team_falling_graphite',
    alt: 'Evisen Team Falling Graphite',
  },
  {
    brand: 'Evisen',
    model: 'Team',
    title: 'Glory',
    imgBaseName: 'evisen_team_glory',
    alt: 'Evisen Team Glory',
  },
  {
    brand: 'Frog',
    model: 'Chris Milic',
    title: 'Tree Trunk',
    imgBaseName: 'frog_chris_milic_tree_trunk',
    alt: 'Frog Chris Milic Tree Trunk',
  },
  {
    brand: 'Frog',
    model: 'Team',
    title: 'X Ploding Joy',
    imgBaseName: 'frog_team_x_ploding_joy',
    alt: 'Frog Team X Ploding Joy',
  },
  {
    brand: 'Girl',
    id: 'girl',
    model: 'Geering Suzuki',
    title: 'Method',
    imgBaseName: 'girl_geering_suzuki_method',
    alt: 'Girl Geering Suzuki Method',
  },
  {
    brand: 'Girl',
    id: 'girl',
    model: 'Andrew Brophy',
    title: 'Kinsey Code',
    imgBaseName: 'girl_andrew_brophy_kinsey_code',
    alt: 'Girl Andrew Brophy Kinsey Code',
  },
  {
    brand: 'Glass House',
    model: 'Danny DiCola',
    title: 'Abyss',
    imgBaseName: 'glass_house_danny_dicola_abyss',
    alt: 'Glass House Danny DiCola Abyss',
  },
  {
    brand: 'Glass House',
    model: 'Pat Burke',
    title: 'Butterfly',
    imgBaseName: 'glass_house_pat_burke_butterfly',
    alt: 'Glass House Pat Burke Butterfly',
  },
  {
    brand: 'Glass House',
    model: 'Team',
    title: 'Eye Witness Black / Orange',
    imgBaseName: 'glass_house_team_eye_witness_black_orange',
    alt: 'Glass House Team Eye Witness Black / Orange',
  },
  {
    brand: 'Grizzly',
    model: 'Team',
    title: 'Fabric',
    imgBaseName: 'grizzly_team_fabric',
    alt: 'Grizzly Team Fabric',
  },
  {
    brand: 'Grizzly',
    model: 'Team',
    title: 'Lend A Hand',
    imgBaseName: 'grizzly_team_lend_a_hand',
    alt: 'Grizzly Team Lend A Hand',
  },
  {
    brand: 'Grizzly',
    model: 'Team',
    title: 'Half Dome',
    imgBaseName: 'grizzly_team_half_dome',
    alt: 'Grizzly Team Half Dome',
  },
  {
    brand: 'Grizzly',
    model: 'Team',
    title: 'Taste The Rainbow',
    imgBaseName: 'grizzly_team_taste_the_rainbow',
    alt: 'Grizzly Team Taste The Rainbow',
  },
  {
    brand: 'Globe',
    model: 'Team',
    title: 'G1 Sol Mates',
    imgBaseName: 'globe_team_g1_sol_mates',
    alt: 'Globe Team G1 Sol Mates',
  },
  {
    brand: 'GX1000',
    model: 'Sean Greene',
    title: 'Killer Whale',
    imgBaseName: 'gx1000_sean_greene_killer_whale',
    alt: 'GX1000 Sean Greene Killer Whale',
  },
  {
    brand: 'GX1000',
    model: 'Team',
    title: 'Gate',
    imgBaseName: 'gx1000_team_gate',
    alt: 'GX1000 Team Gate',
  },
  {
    brand: 'GX1000',
    model: 'Team',
    title: 'Golden Gate',
    imgBaseName: 'gx1000_team_golden_gate',
    alt: 'GX1000 Team Golden Gate',
  },
  {
    brand: 'GX1000',
    model: 'Team',
    title: 'Twenty Zero Two',
    imgBaseName: 'gx1000_team_twenty_zero_two',
    alt: 'GX1000 Team Twenty Zero Two',
  },
  {
    brand: 'Habitat',
    model: 'Team',
    title: 'Lunar Lux',
    imgBaseName: 'habitat_team_lunar_lux',
    alt: 'Habitat Team Lunar Lux',
  },
  {
    brand: 'Hardbody',
    model: 'Hjalte Halberg',
    title: 'Bike Underneath',
    imgBaseName: 'hardbody_hjalte_halberg_bike_underneath',
    alt: 'Hardbody Hjalte Halberg Bike Underneath',
  },
  {
    brand: 'Hardbody',
    model: 'Team',
    title: 'Diamond Plate Grey',
    imgBaseName: 'hardbody_team_diamond_plate_grey',
    alt: 'Hardbody Team Diamond Plate Grey',
  },
  {
    brand: 'Hockey',
    model: 'Team',
    title: 'Intermission',
    imgBaseName: 'hockey_team_intermission',
    alt: 'Hockey Team Intermission',
  },
  {
    brand: 'Hockey',
    model: 'Team',
    title: 'My Friend The Liar',
    imgBaseName: 'hockey_my_friend_the_liar',
    alt: 'Hockey Team My Friend The Liar',
  },
  {
    brand: 'Hockey',
    model: 'Team',
    title: 'Torn',
    imgBaseName: 'hockey_team_torn',
    alt: 'Hockey Team Torn',
  },
  {
    brand: 'IFO',
    model: 'Team',
    title: 'Balance',
    imgBaseName: 'ifo_team_balance',
    alt: 'IFO Team Balance',
  },
  {
    brand: 'Isle',
    model: 'Team',
    title: 'Tweaked Modernism Purgas',
    imgBaseName: 'isle_team_tweaked_modernism_purgas',
    alt: 'Isle Team Tweaked Modernism Purgas',
  },
  {
    brand: 'Isle',
    model: 'Team',
    title: 'Tweaked Modernism Wieser',
    imgBaseName: 'isle_team_tweaked_modernism_wieser',
    alt: 'Isle Team Tweaked Modernism Wieser',
  },
  {
    brand: 'Jacuzzi Unlimited',
    model: 'Jackson Pilz',
    title: 'Head Ache',
    imgBaseName: 'jacuzzi_jackson_pilz_head_ache',
    alt: 'Jacuzzi Unlimited Jackson Pilz Head Ache',
  },
  {
    brand: 'Jacuzzi Unlimited',
    model: 'John Dilo',
    title: 'Hand Held',
    imgBaseName: 'jacuzzi_john_dilo_hand_held',
    alt: 'Jacuzzi Unlimited John Dilo Hand Held',
  },
  {
    brand: 'Jacuzzi Unlimited',
    model: 'Louie Barletta',
    title: 'Toy',
    imgBaseName: 'jacuzzi_louie_barletta_toy',
    alt: 'Jacuzzi Unlimited Louie Barletta Toy',
  },
  {
    brand: 'Jacuzzi Unlimited',
    model: 'Team',
    title: 'The Musical EX7',
    imgBaseName: 'jacuzzi_team_the_musical_ex7',
    alt: 'Jacuzzi Unlimited Team The Musical EX7',
  },
  {
    brand: 'Krooked',
    model: 'Brad Cromer',
    title: 'Mad King',
    imgBaseName: 'krooked_brad_cromer_mad_king',
    alt: 'Krooked Brad Cromer Mad King',
  },
  {
    brand: 'Krooked',
    model: 'Team',
    title: 'Eyes Black',
    imgBaseName: 'krooked_team_eyes_black',
    alt: 'Krooked Team Eyes Black',
  },
  {
    brand: 'Lesque',
    model: 'Kenya Okuno',
    title: 'Horizon',
    imgBaseName: 'lesque_kenya_okuno_horizon',
    alt: 'Lesque Kenya Okuno Horizon',
  },
  {
    brand: 'Lesque',
    model: 'Ryo Motohashi',
    title: 'Velvet Step',
    imgBaseName: 'lesque_ryo_motohashi_velvet_step',
    alt: 'Lesque Ryo Motohashi Velvet Step',
  },
  {
    brand: 'Lesque',
    model: 'Mana Sasaki',
    title: 'Drive',
    imgBaseName: 'lesque_mana_sasaki_drive',
    alt: 'Lesque Mana Sasaki Drive',
  },
  {
    brand: 'Lesque',
    model: 'Team',
    title: 'Ivory Monogram',
    imgBaseName: 'lesque_team_ivory_monogram',
    alt: 'Lesque Team Ivory Monogram',
  },
  {
    brand: 'Limosine',
    model: 'Aaron Loreth',
    title: 'Hail Fail',
    imgBaseName: 'limosine_aaron_loreth_hail_fail',
    alt: 'Limosine Aaron Loreth Hail Fail',
  },
  {
    brand: 'Limosine',
    model: 'Aaron Loreth',
    title: 'Angel',
    imgBaseName: 'limosine_aaron_loreth_angel',
    alt: 'Limosine Aaron Loreth Angel',
  },
  {
    brand: 'Limosine',
    model: 'Cyrus Bennett',
    title: 'Limo Signal',
    imgBaseName: 'limosine_cyrus_bennett_limo_signal',
    alt: 'Limosine Cyrus Bennett Limo Signal',
  },
  {
    brand: 'Limosine',
    model: 'Cyrus Bennett',
    title: 'Morph',
    imgBaseName: 'limosine_cyrus_bennett_morph',
    alt: 'Limosine Cyrus Bennett Morph',
  },
  {
    brand: 'Limosine',
    model: 'Karim Callender',
    title: 'Third Eye',
    imgBaseName: 'limosine_karim_callender_third_eye',
    alt: 'Limosine Max Palmer Soul Crusher',
  },
  {
    brand: 'Limosine',
    model: 'Max Palmer',
    title: 'Soul Crusher',
    imgBaseName: 'limosine_max_palmer_soul_crusher',
    alt: 'Limosine Max Palmer Soul Crusher',
  },
  {
    brand: 'Limosine',
    model: 'Team',
    title: 'Cat Metallic',
    imgBaseName: 'limosine_team_cat_metallic',
    alt: 'Limosine Team Cat Metallic',
  },
  {
    brand: 'Limosine',
    model: 'Team',
    title: 'Snake Pit',
    imgBaseName: 'limosine_team_snake_pit',
    alt: 'Limosine Team Snake Pit',
  },
  {
    brand: 'Magenta',
    model: 'Leo Valls',
    title: 'Metro Purple',
    imgBaseName: 'magenta_leo_valls_metro_purple',
    alt: 'Magenta Leo Valls Metro Purple',
  },
  {
    brand: 'Magenta',
    model: 'Glen Fox & Ben Gore',
    title: 'Metro',
    imgBaseName: 'magenta_glen_foxandben_gore_metro',
    alt: 'Magenta Glen Fox & Ben Gore Metro',
  },
  {
    brand: 'Magenta',
    model: 'Shogo Zama',
    title: 'Metro',
    imgBaseName: 'magenta_shogo_zama_metro',
    alt: 'Magenta Shogo Zama Metro',
  },
  {
    brand: 'Opera',
    model: 'Clay Kreiner',
    title: 'Cutter EX7',
    imgBaseName: 'opera_clay_kreiner_cutter_ex7',
    alt: 'Opera Clay Kreiner Cutter EX7',
  },
  {
    brand: 'Opera',
    model: 'Clay Kreiner',
    title: 'Grooves',
    imgBaseName: 'opera_clay_kreiner_grooves',
    alt: 'Opera Clay Kreiner Grooves',
  },
  {
    brand: 'Opera',
    model: 'Jack Fardell',
    title: 'Organ',
    imgBaseName: 'opera_jack_fardell_organ',
    alt: 'Opera Jack Fardell Organ',
  },
  {
    brand: 'Opera',
    model: 'Nassim Lachhab',
    title: 'Gift',
    imgBaseName: 'opera_nassim_lachhab_gift',
    alt: 'Opera Nassim Lachhab Gift',
  },
  {
    brand: 'Opera',
    model: 'Team',
    title: 'Bureaucracy',
    imgBaseName: 'opera_team_bureaucracy',
    alt: 'Opera Team Bureaucracy',
  },
  {
    brand: 'Opera',
    model: 'Team',
    title: 'Grip',
    imgBaseName: 'opera_team_grip',
    alt: 'Opera Team Grip',
  },
  {
    brand: 'Pass~Port',
    model: 'Dean Palmer',
    title: 'Sr Spoons',
    imgBaseName: 'pass-port_dean_palmer_sr_spoons',
    alt: 'Pass~Port Dean Palmer Sr Spoons',
  },
  {
    brand: 'Polar',
    model: 'Aaron Herrington',
    title: 'Bunny',
    imgBaseName: 'polar_aaron_herrington_bunny',
    alt: 'Polar Aaron Herrington Bunny',
  },
  {
    brand: 'Polar',
    model: 'David Strenstrom',
    title: 'Tape and Panther',
    imgBaseName: 'polar_david_strenstrom_tapeandpanther',
    alt: 'Polar David Strenstrom Tape and Panther',
  },
  {
    brand: 'Polar',
    model: 'David Strenstrom',
    title: 'Toba',
    imgBaseName: 'polar_david_strenstrom_toba',
    alt: 'Polar David Strenstrom Toba',
  },
  {
    brand: 'Polar',
    model: 'Nick Boserio',
    title: 'Fruit Lady',
    imgBaseName: 'polar_nick_boserio_fruit_lady',
    alt: 'Polar Nick Boserio Fruit Lady',
  },
  {
    brand: 'Polar',
    model: 'Nick Boserio',
    title: 'Useless Wooden',
    imgBaseName: 'polar_nick_boserio_useless_wooden',
    alt: 'Polar Nick Boserio Useless Wooden',
  },
  {
    brand: 'Polar',
    model: 'Paul Grund',
    title: 'Gardner',
    imgBaseName: 'polar_paul_grund_gardner',
    alt: 'Polar Paul Grund Gardner',
  },
  {
    brand: 'Polar',
    model: 'Paul Grund',
    title: 'Stuntman',
    imgBaseName: 'polar_paul_grund_stuntman',
    alt: 'Polar Paul Grund Stuntman',
  },
  {
    brand: 'Polar',
    model: 'Roman Gonzalez',
    title: 'Stay In Motion Blue',
    imgBaseName: 'polar_roman_gonzalez_stay_in_motion_blue',
    alt: 'Polar Roman Gonzalez Stay In Motion Blue',
  },
  {
    brand: 'Polar',
    model: 'Shin Sanbongi',
    title: 'Shin City',
    imgBaseName: 'polar_shin_sanbongi_shin_city',
    alt: 'Polar Shin Sanbongi Shin City',
  },
  {
    brand: 'Polar',
    model: 'Team',
    title: 'BS Smith Cream',
    imgBaseName: 'polar_team_bs_smith_cream',
    alt: 'Polar Team BS Smith Cream',
  },
  {
    brand: 'Polar',
    model: 'Team',
    title: 'Happy Sad Detroit',
    imgBaseName: 'polar_team_happy_sad_detroit',
    alt: 'Polar Team Happy Sad Detroit',
  },
  {
    brand: 'Polar',
    model: 'Team',
    title: 'Searching For Peace',
    imgBaseName: 'polar_team_searching_for_peace',
    alt: 'Polar Team Searching For Peace',
  },
  {
    brand: 'Premium',
    model: 'Kousei Toyooka',
    title: 'Anthisi Ice Tie-Dye Nebula',
    imgBaseName: 'premium_kousei_toyooka_anthisi_ice_tie-dye_nebula',
    alt: 'Premium Kousei Toyooka Anthisi Ice Tie-Dye Nebula',
  },
  {
    brand: 'Primitive',
    model: 'Carlos Ribeiro',
    title: 'Journey',
    imgBaseName: 'primitive_carlos_ribeiro_journey',
    alt: 'Primitive Carlos Ribeiro Journey',
  },
  {
    brand: 'Primitive',
    model: 'Paul Rodriguez',
    title: 'Contact',
    imgBaseName: 'primitive_paul_rodriguez_contact',
    alt: 'Primitive Paul Rodriguez Contact',
  },
  {
    brand: 'Primitive',
    model: 'Team',
    title: 'Euro Slant Core Black',
    imgBaseName: 'primitive_team_euro_slant_core_black',
    alt: 'Primitive Team Euro Slant Core Black',
  },
  {
    brand: 'Primitive',
    model: 'Team',
    title: 'Hello',
    imgBaseName: 'primitive_team_hello',
    alt: 'Primitive Team Hello',
  },
  {
    brand: 'Quasi',
    model: 'Bobby De Keyzer',
    title: 'Timeline',
    imgBaseName: 'quasi_bobby_de_keyzer_timeline',
    alt: 'Quasi Bobby De Keyzer Timeline',
  },
  {
    brand: 'Quasi',
    model: 'Jake Johnson',
    title: 'Milan',
    imgBaseName: 'quasi_jake_johnson_milan',
    alt: 'Quasi Jake Johnson Milan',
  },
  {
    brand: 'Quasi',
    model: 'Johnson Boomerang',
    title: '-',
    imgBaseName: 'quasi_johnson_boomerang',
    alt: 'Quasi Johnson Boomerang',
  },
  {
    brand: 'Quasi',
    model: 'Team',
    title: 'Edger',
    imgBaseName: 'quasi_team_edger',
    alt: 'Quasi Team Edger',
  },
  {
    brand: 'Quasi',
    model: 'Team',
    title: 'Proto',
    imgBaseName: 'quasi_team_proto',
    alt: 'Quasi Team Proto',
  },
  {
    brand: 'Quasi',
    model: 'Team',
    title: 'Proto 1',
    imgBaseName: 'quasi_team_proto_1',
    alt: 'Quasi Team Proto 1',
  },
  {
    brand: 'Real',
    model: 'Ishod Wair',
    title: 'Metamorphosis',
    imgBaseName: 'real_ishod_wair_metamorphosis',
    alt: 'Real Ishod Wair Metamorphosis',
  },
  {
    brand: 'Real',
    model: 'Mason Silva',
    title: 'On The Rocks',
    imgBaseName: 'real_mason_silva_on_the_rocks',
    alt: 'Real Mason Silva On The Rocks',
  },
  {
    brand: 'Real',
    model: 'Mason Silva',
    title: 'Record Scratch',
    imgBaseName: 'real_mason_silva_record_scratch',
    alt: 'Real Mason Silva Record Scratch',
  },
  {
    brand: 'Real',
    model: 'Team',
    title: 'Zion Canopy',
    imgBaseName: 'real_team_zion_canopy',
    alt: 'Real Team Zion Canopy',
  },
  {
    brand: 'Real',
    model: 'Wair Cerebrus',
    title: 'DBX',
    imgBaseName: 'real_wair_cerebrus_dbx',
    alt: 'Real Wair Cerebrus DBX',
  },
  {
    brand: 'Santa Cruz',
    model: 'Santa Cruz x Stranger',
    title: 'Things Season 5',
    imgBaseName: 'santa_cruz_santacruzxstranger_things_season_5',
    alt: 'Santa Cruz Santa Cruz x Stranger Things Season 5',
  },
  {
    brand: 'Snack',
    model: 'Ty Beall',
    title: 'Junk Removal',
    imgBaseName: 'snack_ty_beall_junk_removal',
    alt: 'Snack Ty Beall Junk Removal',
  },
  {
    brand: 'Sprinkles',
    model: 'Connor Kammerer',
    title: 'Debut',
    imgBaseName: 'sprinkles_connor_kammerer_debut',
    alt: 'Sprinkles Connor Kammerer Debut',
  },
  {
    brand: 'Sprinkles',
    model: 'Team',
    title: 'Caseload',
    imgBaseName: 'sprinkles_team_caseload',
    alt: 'Sprinkles Team Caseload',
  },
  {
    brand: 'Sprinkles',
    model: 'Team',
    title: 'Sheltered',
    imgBaseName: 'sprinkles_team_sheltered',
    alt: 'Sprinkles Team Sheltered',
  },
  {
    brand: 'Swim',
    model: 'Justin Drysen',
    title: 'Debut',
    imgBaseName: 'swim_justin_drysen_debut',
    alt: 'Swim Justin Drysen Debut',
  },
  {
    brand: 'Tactics',
    model: 'Team',
    title: 'Air Nowhere',
    imgBaseName: 'tactics_team_air_nowhere',
    alt: 'Tactics Team Air Nowhere',
  },
  {
    brand: 'Tactics',
    model: 'Team',
    title: 'Deconstruct',
    imgBaseName: 'tactics_team_deconstruct',
    alt: 'Tactics Team Deconstruct',
  },
  {
    brand: 'Tactics',
    model: 'Team',
    title: 'Fingerboard',
    imgBaseName: 'tactics_team_fingerboard',
    alt: 'Tactics Team Fingerboard',
  },
  {
    brand: 'Tactics',
    model: 'Team',
    title: 'Lobotomy',
    imgBaseName: 'tactics_team_lobotomy',
    alt: 'Tactics Team Lobotomy',
  },
  {
    brand: 'Tactics',
    model: 'Team',
    title: 'Multnowhere Falls',
    imgBaseName: 'tactics_team_multnowhere_falls',
    alt: 'Tactics Team Multnowhere Falls',
  },
  {
    brand: 'Tactics',
    model: 'Team',
    title: 'Oval Logo',
    imgBaseName: 'tactics_team_oval_logo',
    alt: 'Tactics Team Oval Logo',
  },
  {
    brand: 'Tactics',
    model: 'Team',
    title: 'Robot In A Chair',
    imgBaseName: 'tactics_team_robot_in_a_chair',
    alt: 'Tactics Team Robot In A Chair',
  },
  {
    brand: 'Tactics',
    model: 'Team',
    title: 'Sand Monsters',
    imgBaseName: 'tactics_team_sand_monsters',
    alt: 'Tactics Team Sand Monsters',
  },
  {
    brand: 'Tactics',
    model: 'Team',
    title: 'Unsurpassed Insignificance',
    imgBaseName: 'tactics_team_unsurpassed_insignificance',
    alt: 'Tactics Team Unsurpassed Insignificance',
  },
  {
    brand: 'Theories',
    model: 'Nyle Lovett',
    title: 'Majesties',
    imgBaseName: 'theories_nyle_lovett_majesties',
    alt: 'Theories Nyle Lovett Majesties',
  },
  {
    brand: 'Theories',
    model: 'Team',
    title: 'Rasputin V3',
    imgBaseName: 'theories_team_rasputin_v3',
    alt: 'Theories Team Rasputin V3',
  },
  {
    brand: 'Tightbooth',
    model: 'Team',
    title: 'Pass The Pie',
    imgBaseName: 'tightbooth_team_pass_the_pie',
    alt: 'Tightbooth Team Pass The Pie',
  },
  {
    brand: 'Tightbooth',
    model: 'Team',
    title: 'Shredder',
    imgBaseName: 'tightbooth_team_shredder',
    alt: 'Tightbooth Team Shredder',
  },
  {
    brand: 'T.I.M.E.',
    model: 'Team',
    title: 'Test Press',
    imgBaseName: 'time_team_test_press',
    alt: 'T.I.M.E. Team Test Press',
  },
  {
    brand: 'T.I.M.E.',
    model: 'Team',
    title: 'Valleys',
    imgBaseName: 'time_team_valleys',
    alt: 'T.I.M.E. Team Valleys',
  },
] 

export const brands = [
  {
    name: 'Alien Workshop',
    id: 'alien_workshop',
    iconFileName: 'logo_alien_workshop.svg',
    desc: <>Alien Workshop was founded in 1990 by Chris Carter, Mike Hill, and Neil Blender.<br />Based in Dayton, Ohio.<br />Alien has abducted top pros such as Rob Dyrdek, Josh Kalis, Jason Dill, Anthony van Engelen, and many more.</>,
    link: 'https://www.alienworkshop.com/'
  },
  {
    name: 'Alva Skates',
    id: 'alva_skates',
    iconFileName: 'logo_alva.svg',
    desc: <>Alva Skateboards was founded in 1977 by legendary skater Tony Alva, one of the founders of the iconic &quot;Z-Boys&quot; skateboard crew.<br />Based in Santa Monica, California, Alva is renowned for its innovative designs and strong commitment to skateboarding culture.</>,
    link: 'https://alva-skates.com/'
  },
  {
    name: 'Antihero',
    id: 'antihero',
    iconFileName: 'logo_antihero.webp',
    desc: <>Anti Hero Skateboards was founded by professional skateboarder Julien Stranger in 1995. <br />Anti Hero is most recognized by its Eagle logo and hard hitting team, including John Cardiel, Grant Taylor, Tony Trujillo, and others.</>,
    link: 'https://www.antiheroskateboards.com/'
  },
  {
    name: 'April',
    id: 'april',
    iconFileName: 'logo_april.webp',
    desc: <>April Skateboards was started by Australian skateboarder Shane O&apos;Neill.<br />April sponsors some of the most talented skaters on the planet.</>,
    link: 'https://aprilskateboards.com/'
  },
  {
    name: 'Baker',
    id: 'baker',
    iconFileName: 'logo_baker.svg',
    desc: <>Andrew Reynolds&apos; Baker Skateboards has been at the root of debauchery and insane skating for 25 years. <br />Baker&apos;s Brand Logo continues to be one of skateboarding&apos;s top selling graphics.</>,
    link: 'https://bakerskateboards.com/'
  },
  {
    name: 'birdhouse',
    id: 'birdhouse',
    iconFileName: 'logo_birdhouse.svg',
    desc: <>Birdhouse was founded by Tony Hawk in 1992 with the premise, &quot;if you love something, you support it and nurture it&quot;.</>,
    link: 'https://birdhouseskateboards.com/'
  },
  {
    name: 'Black Label',
    id: 'black_label',
    iconFileName: 'logo_blacklabel.webp',
    desc: <>Black Label Skateboards was founded in 1988 by professional skateboarder John Lucero.</>,
    link: 'https://www.blacklabelskates.com/'
  },
  {
    name: 'Blueprint',
    id: 'blueprint',
    iconFileName: 'logo_blueprint.webp',
    desc: <>Blueprint skateboards was established in 1995 as one of the UK&apos;s early skate brands.</>,
    link: 'https://www.blueprintskateboards.com/'
  },
  {
    name: 'Chocolate',
    id: 'chocolate',
    iconFileName: 'logo_chocolate.svg',
    desc: <>When the Girl Skateboards team was overflowing with talent, Chocolate Skateboards was born.<br />Chocolate is known for its diverse team, legendary videos, and great product.</>,
    link: 'https://www.chocolateskateboards.com/'
  },
  {
    name: 'Deathwish',
    id: 'deathwish',
    iconFileName: 'logo_deathwish.svg',
    desc: <>Baker has a Deathwish. Out of Baker Boys Distribution comes Deathwish Skateboards.</>,
    link: 'https://www.deathwishskateboards.com/'
  },
  {
    name: 'DGK',
    id: 'dgk',
    iconFileName: 'logo_dgk.svg',
    desc: <>DGK skateboard decks keep the fun and grit in the graphics.<br />Founded by professional skateboarder Stevie Williams.</>,
    link: 'https://www.dgk.com/'
  },
  {
    name: 'EDGLRD',
    id: 'edglrd',
    iconFileName: 'logo_edglrd.svg',
    desc: <>EDGLRD was founded by Harmony Korine, who is known for movie director, screenwriter, etc.</>,
    link: 'https://www.edglrd.com/'
  },
  {
    name: 'Girl',
    id: 'girl',
    iconFileName: 'logo_girl.svg',
    desc: <>Girl Skateboards has a stacked team of pro skaters, from legends like Mike Carroll, Rick Howard, and Rick McCrank to young rippers like Simon Bannerot, Tyler Pacheco, Sean Malto, and Breana Geering. </>,
    link: 'https://www.girlskateboards.com/'
  },
]

